apiVersion: apps/v1
kind: Deployment
metadata:
  name: updated-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: updated-mysql/mysql-server:v1  # Corrected image name format
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: passwrd
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: "1234"  # Enclosed the password in quotes
            - name: MYSQL_DATABASE
              value: Readings
          ports:
            - containerPort: 3307
              name: mysql
