apiVersion: apps/v1
kind: Deployment
metadata:
  name: Updated-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: Updated-mysql/mysql-server
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: passwrd
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: 1234    #changed the password
            - name: MYSQL_DATABASE
              value: Readings
          ports:
            - containerPort: 3307 #changed the port number to 3307 from 3306
              name: mysql
